### ISSUE TITLE
Add the images to your local registry: Docker procedure

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/astra-control-center-2304#2]
### Page URL

https://docs.netapp.com/us-en/astra-control-center-2304/get-started/install_acc.html#add-the-images-to-your-local-registry

### Page title

Install Astra Control Center using the standard process

### Summary

Hi,

the procedure points to a file called "acc.manifest.bundle.yaml" which does not exist...
What is the correct file to use ?
- _acc.manifest.yaml_ available in the root of the tarball, but which does not contain any information about images
-  _astra-control-center-23.07.0-25.manifest_ which needs to be downloaded from the NetApp site & has images information

++

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@YvosOnTheHub sorry for the delay. I see the following at the root of the bundle:
``
/acc,
/kubectl-astra,
acc.manifest.bundle.yaml
``
the acc.manifest.yaml is within /acc. Does that help? 

Also, the link you cited is the 23.04 repo. The current repo covers 23.07 install processes which appear to be identical for this procedure. Just wanted to draw that to your attention as some things have changed for 23.07.

**Comment by netapp-dbagwell** [comment]
We don't mention the /kubectl-astra directory and that may be some of the confusion. I'll update the docs to fix this in 23.07.

**Comment by YvosOnTheHub** [comment]
oh right !
as I _untarred_ the tgz in the root of my home dir, the bundle was hidden amongst other stuff
hence the reflex to directly enter the _acc_ directory & not find the bundle file...
sorry about that... thanks for adding the kubectl-astra, makes the visualisation much clearer
++
